language: c++
install:
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install libsfml-dev
script:
  - cmake . -DSFML_DIR=${TRAVIS_BUILD_DIR}/
  - make
