
install:
  - sudo apt-get install libarmadillo-dev
  - sudo apt-get install libgtest-dev
  - wget https://www.sfml-dev.org/files/SFML-2.5.0-linux-gcc-64-bit.tar.gz
  - mkdir sfml_tmp
  - tar -xzvf SFML-2.5.0-linux-gcc-64-bit.tar.gz -C sfml_tmp
  - bash configure.sh
  - cmake . -DSFML_DIR=${TRAVIS_BUILD_DIR}/sfml_tmp/SFML-2.5.0/lib/cmake/SFML
  - make
